---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pv-nginx-log
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/log/nginx"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-pvc-nginx-log
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

