---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pv-sample-01
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  portworxVolume:
  volumeID: "pv001"     
  hostPath:
    path: "/opt/lg-vol-mnt/sample-01"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-pvc-sample-01
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

