version: "2.0"
services:
  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
  kibana:
    #image: kb-logtrail:latest
    image: nik786/kb-logtrail:v.7.2.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - elk
networks:
  elk:
    driver: bridge
