---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pv-es-log
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/lg-vol-mnt/es/es-log"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-pvc-es-log
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

