---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pv-es-logs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/log/elasticsearch"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-pvc-es-logs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

