---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pv-es-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/lg-vol-mnt/es/es-data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-pvc-es-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1.5Gi

