---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/lg-vol-mnt/kibana/plugins"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kibana-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

