apiVersion: v1
kind: ConfigMap
metadata:
  name: logtrail-config
data:
  logtrail.json: |
    {
        "version" : 1,
        "index_patterns" : [
        {      
            "es": {
                "default_index": "logstash-*"
            },
            "tail_interval_in_seconds": 10,
            "es_index_time_offset_in_seconds": 0,
            "display_timezone": "local",
            "display_timestamp_format": "MMM DD HH:mm:ss",
            "max_buckets": 500,
            "default_time_range_in_days" : 0,
            "max_hosts": 100,
            "max_events_to_keep_in_viewer": 5000,
            "fields" : {
                "mapping" : {
                  "timestamp" : "@timestamp",
                  "message": "log",
        	  "pod_name": "kubernetes.pod_name"

                },
                "message_format": "{{{log}}}"
            },
            "color_mapping" : {
            }
        }]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    ---
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: http://elasticsearch:9200
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        #image: docker.elastic.co/kibana/kibana-oss:7.2.0 # or your image
        #image: kub/kibana-logtrail-nik
        #image: sh4d1/kibana-logtrail:7.2.0
        image: nik786/kb-logtrail:7.2.0
        #command: ["/bin/sh"]
        #args: ["-c","/bin/sleep 86400"]
        env:
        - name: CLUSTER_NAME
          value: esdb # the name of your ES cluster
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: http
        readinessProbe:
          httpGet:
            path: /api/status
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
          - name: config
            mountPath: /usr/share/kibana/config
            readOnly: true
          - name: logtrail-config
            mountPath: /usr/share/kibana/plugins/logtrail
          - name: kibana-plugins
            mountPath: /usr/share/kibana/plugins
      volumes:
        - name: config
          configMap:
            name: kibana-config
        - name: logtrail-config
          configMap:
            name: logtrail-config
        - name: kibana-plugins
          persistentVolumeClaim:                                                                                   
            claimName: kibana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 80
    targetPort: http
  type: NodePort

